1131 dockerification
enspirit/talktome pull request #4
Opened 2021-04-09 11:19 UTC by OSdave

2021-04-09 12:43 UTC, blambeau requested changes

2021-04-09 12:43 UTC, blambeau commented on lib/talktome/app.rb
> +    post '/contact' do
`/contact-us/`

2021-04-09 12:43 UTC, blambeau commented on lib/talktome/app.rb
> +        raise ::Talktome::InvalidEmailError if info['confirmEmail'] && info['confirmEmail'] =~ /^[^@]+@[^@]+$/
Document the fact that this is a honeypot.

2021-04-09 12:43 UTC, blambeau commented on lib/talktome/app.rb
> +        TALKTOME = Talktome::Client::Local.new(Path(info['folder']['data']))
Don't do this. Security issue.

2021-04-09 12:43 UTC, blambeau commented on spec/app/test_app.rb
> +        File.open('/home/david/Desktop/response.html', 'w') { |file| file.write(last_response.body)}
Remove.

2021-04-09 12:52 UTC, blambeau commented
Regarding folder, template & from:

1. Folder = convention: a `./talktome` folder must exists (typically mounted as a volume). 

Typically used as follows (Dockerfile):

```
FROM enspirit/talktome:latest
COPY ./mail-templates /app/talktome/
```

Another way (docker-compose):

```
services:
  talktome:
    image: enspirit/talktome
    volumes:
      - ./mail-templates/:/app/talktome/
```

2. Template = convention. `/contact-us` requires a `contact-us/email.md` in the templates.

3. Regarding the `FROM`. Use the `TALKTOME_EMAIL_DEFAULT_FROM` environment variables (must be set by Devops).

4.' (option) We could enhance Talktome to have a better notion of 'default_email' at configuration time, with more env variables for subject, to, from, reply-to etc. Every mail sent would then be a overriding of the default email.

2021-04-13 14:48 UTC, OSdave commented
Jekins test this please.

2021-04-14 15:25 UTC, OSdave commented
@blambeau let me know if you think I can merge this branch into master and go on with the integration for exquando

2021-04-15 14:19 UTC, blambeau requested changes

2021-04-15 14:19 UTC, blambeau commented on lib/talktome.rb
> +require 'talktome/app'
Don't require by default, move it to config.ru

2021-04-15 14:21 UTC, merged